apiVersion: v1
kind: Pod
metadata:
  name: ubuntuapp
  labels:
    app: ubuntuapp
  annotations: {
    "opencontrail.org/network" : '{"domain":"default-domain", "project": "admin", "name":"MGMT-VN"}'
  }
spec:
  containers:
    - name: ubuntuapp
      image: ubuntu-upstart