
interfaces:
    - name: xe-0/0/0
      description: "connect srv1"
    - name: xe-0/0/1
      description: "connect srv2"
    - name: xe-0/0/2
      description: "connect srv3"
    - name: xe-0/0/3
      description: "connect srv4"
    - name: xe-0/0/4
      description: "connect bms"
